// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../network/manager.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Contact> addContact({required String name, required String address}) =>
    RustLib.instance.api.crateApiContactsAddContact(name: name, address: address);

List<Contact> getContacts() => RustLib.instance.api.crateApiContactsGetContacts();

Future<String> removeContact({required String contactId}) =>
    RustLib.instance.api.crateApiContactsRemoveContact(contactId: contactId);

Future<String> updateContactTrustLevel({required String contactId, required TrustLevel trustLevel}) =>
    RustLib.instance.api.crateApiContactsUpdateContactTrustLevel(contactId: contactId, trustLevel: trustLevel);

Contact getContactById({required String contactId}) =>
    RustLib.instance.api.crateApiContactsGetContactById(contactId: contactId);
