// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../events/bus.dart';
import '../frb_generated.dart';
import '../network/manager.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> startEventListener() => RustLib.instance.api.crateApiEventsStartEventListener();

List<AppEvent> getPendingEvents() => RustLib.instance.api.crateApiEventsGetPendingEvents();

bool hasPendingEvents() => RustLib.instance.api.crateApiEventsHasPendingEvents();

String clearEventQueue() => RustLib.instance.api.crateApiEventsClearEventQueue();

Future<String> emitCustomEvent({required String eventType, required String data}) =>
    RustLib.instance.api.crateApiEventsEmitCustomEvent(eventType: eventType, data: data);

int getEventQueueSize() => RustLib.instance.api.crateApiEventsGetEventQueueSize();
