// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../network/manager.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> sendTextMessage({required String contactId, required String content}) =>
    RustLib.instance.api.crateApiMessagesSendTextMessage(contactId: contactId, content: content);

Future<String> sendFileMessage({required String contactId, required String filePath, required String fileName}) =>
    RustLib.instance.api.crateApiMessagesSendFileMessage(contactId: contactId, filePath: filePath, fileName: fileName);

Future<List<ChatMessage>> getMessages({required String contactId, required int limit, required int offset}) =>
    RustLib.instance.api.crateApiMessagesGetMessages(contactId: contactId, limit: limit, offset: offset);

Future<List<ChatMessage>> getRecentMessages({required String contactId, required int limit}) =>
    RustLib.instance.api.crateApiMessagesGetRecentMessages(contactId: contactId, limit: limit);

int getUnreadMessageCount({required String contactId}) =>
    RustLib.instance.api.crateApiMessagesGetUnreadMessageCount(contactId: contactId);
