// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/contacts.dart';
import 'api/core.dart';
import 'api/events.dart';
import 'api/messages.dart';
import 'api/network.dart';
import 'dart:async';
import 'dart:convert';
import 'events/bus.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'network/manager.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -338652500;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'shadowghost',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Contact> crateApiContactsAddContact({required String name, required String address});

  String crateApiEventsClearEventQueue();

  String crateApiNetworkConnectToPeer({required String peerAddress});

  String crateApiNetworkDisconnectFromPeer({required String peerId});

  Future<String> crateApiEventsEmitCustomEvent({required String eventType, required String data});

  Future<String> crateApiCoreGenerateMyLink();

  List<PeerData> crateApiNetworkGetConnectedPeers();

  Contact crateApiContactsGetContactById({required String contactId});

  List<Contact> crateApiContactsGetContacts();

  int crateApiEventsGetEventQueueSize();

  Future<List<ChatMessage>> crateApiMessagesGetMessages({
    required String contactId,
    required int limit,
    required int offset,
  });

  String crateApiNetworkGetMyNetworkAddress();

  NetworkStats crateApiNetworkGetNetworkStats();

  List<AppEvent> crateApiEventsGetPendingEvents();

  Future<List<ChatMessage>> crateApiMessagesGetRecentMessages({required String contactId, required int limit});

  int crateApiMessagesGetUnreadMessageCount({required String contactId});

  bool crateApiEventsHasPendingEvents();

  Future<String> crateApiCoreInitializeCore();

  bool crateApiCoreIsCoreInitialized();

  bool crateApiNetworkIsNetworkActive();

  BigInt crateApiNetworkPingPeer({required String peerId});

  Future<String> crateApiContactsRemoveContact({required String contactId});

  Future<String> crateApiMessagesSendFileMessage({
    required String contactId,
    required String filePath,
    required String fileName,
  });

  Future<String> crateApiMessagesSendTextMessage({required String contactId, required String content});

  String crateApiNetworkSetNetworkConfig({required int maxPeers, required int port});

  String crateApiCoreShutdownCore();

  String crateApiNetworkStartDiscovery();

  Future<String> crateApiEventsStartEventListener();

  Future<String> crateApiCoreStartServer();

  String crateApiNetworkStopDiscovery();

  Future<String> crateApiContactsUpdateContactTrustLevel({required String contactId, required TrustLevel trustLevel});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Contact> crateApiContactsAddContact({required String name, required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(address, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_contact, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiContactsAddContactConstMeta,
        argValues: [name, address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContactsAddContactConstMeta =>
      const TaskConstMeta(debugName: "add_contact", argNames: ["name", "address"]);

  @override
  String crateApiEventsClearEventQueue() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: null),
        constMeta: kCrateApiEventsClearEventQueueConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventsClearEventQueueConstMeta =>
      const TaskConstMeta(debugName: "clear_event_queue", argNames: []);

  @override
  String crateApiNetworkConnectToPeer({required String peerAddress}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerAddress, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkConnectToPeerConstMeta,
        argValues: [peerAddress],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkConnectToPeerConstMeta =>
      const TaskConstMeta(debugName: "connect_to_peer", argNames: ["peerAddress"]);

  @override
  String crateApiNetworkDisconnectFromPeer({required String peerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkDisconnectFromPeerConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkDisconnectFromPeerConstMeta =>
      const TaskConstMeta(debugName: "disconnect_from_peer", argNames: ["peerId"]);

  @override
  Future<String> crateApiEventsEmitCustomEvent({required String eventType, required String data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventType, serializer);
          sse_encode_String(data, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiEventsEmitCustomEventConstMeta,
        argValues: [eventType, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventsEmitCustomEventConstMeta =>
      const TaskConstMeta(debugName: "emit_custom_event", argNames: ["eventType", "data"]);

  @override
  Future<String> crateApiCoreGenerateMyLink() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiCoreGenerateMyLinkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreGenerateMyLinkConstMeta =>
      const TaskConstMeta(debugName: "generate_my_link", argNames: []);

  @override
  List<PeerData> crateApiNetworkGetConnectedPeers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_peer_data, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkGetConnectedPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetConnectedPeersConstMeta =>
      const TaskConstMeta(debugName: "get_connected_peers", argNames: []);

  @override
  Contact crateApiContactsGetContactById({required String contactId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_contact, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiContactsGetContactByIdConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContactsGetContactByIdConstMeta =>
      const TaskConstMeta(debugName: "get_contact_by_id", argNames: ["contactId"]);

  @override
  List<Contact> crateApiContactsGetContacts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_contact, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiContactsGetContactsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContactsGetContactsConstMeta =>
      const TaskConstMeta(debugName: "get_contacts", argNames: []);

  @override
  int crateApiEventsGetEventQueueSize() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiEventsGetEventQueueSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventsGetEventQueueSizeConstMeta =>
      const TaskConstMeta(debugName: "get_event_queue_size", argNames: []);

  @override
  Future<List<ChatMessage>> crateApiMessagesGetMessages({
    required String contactId,
    required int limit,
    required int offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_u_32(offset, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_chat_message, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiMessagesGetMessagesConstMeta,
        argValues: [contactId, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagesGetMessagesConstMeta =>
      const TaskConstMeta(debugName: "get_messages", argNames: ["contactId", "limit", "offset"]);

  @override
  String crateApiNetworkGetMyNetworkAddress() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkGetMyNetworkAddressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetMyNetworkAddressConstMeta =>
      const TaskConstMeta(debugName: "get_my_network_address", argNames: []);

  @override
  NetworkStats crateApiNetworkGetNetworkStats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_network_stats, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkGetNetworkStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetNetworkStatsConstMeta =>
      const TaskConstMeta(debugName: "get_network_stats", argNames: []);

  @override
  List<AppEvent> crateApiEventsGetPendingEvents() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_app_event, decodeErrorData: null),
        constMeta: kCrateApiEventsGetPendingEventsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventsGetPendingEventsConstMeta =>
      const TaskConstMeta(debugName: "get_pending_events", argNames: []);

  @override
  Future<List<ChatMessage>> crateApiMessagesGetRecentMessages({required String contactId, required int limit}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_chat_message, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiMessagesGetRecentMessagesConstMeta,
        argValues: [contactId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagesGetRecentMessagesConstMeta =>
      const TaskConstMeta(debugName: "get_recent_messages", argNames: ["contactId", "limit"]);

  @override
  int crateApiMessagesGetUnreadMessageCount({required String contactId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiMessagesGetUnreadMessageCountConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagesGetUnreadMessageCountConstMeta =>
      const TaskConstMeta(debugName: "get_unread_message_count", argNames: ["contactId"]);

  @override
  bool crateApiEventsHasPendingEvents() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_bool, decodeErrorData: null),
        constMeta: kCrateApiEventsHasPendingEventsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventsHasPendingEventsConstMeta =>
      const TaskConstMeta(debugName: "has_pending_events", argNames: []);

  @override
  Future<String> crateApiCoreInitializeCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiCoreInitializeCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitializeCoreConstMeta =>
      const TaskConstMeta(debugName: "initialize_core", argNames: []);

  @override
  bool crateApiCoreIsCoreInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_bool, decodeErrorData: null),
        constMeta: kCrateApiCoreIsCoreInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreIsCoreInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_core_initialized", argNames: []);

  @override
  bool crateApiNetworkIsNetworkActive() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_bool, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkIsNetworkActiveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkIsNetworkActiveConstMeta =>
      const TaskConstMeta(debugName: "is_network_active", argNames: []);

  @override
  BigInt crateApiNetworkPingPeer({required String peerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_64, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkPingPeerConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPingPeerConstMeta =>
      const TaskConstMeta(debugName: "ping_peer", argNames: ["peerId"]);

  @override
  Future<String> crateApiContactsRemoveContact({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiContactsRemoveContactConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContactsRemoveContactConstMeta =>
      const TaskConstMeta(debugName: "remove_contact", argNames: ["contactId"]);

  @override
  Future<String> crateApiMessagesSendFileMessage({
    required String contactId,
    required String filePath,
    required String fileName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_String(filePath, serializer);
          sse_encode_String(fileName, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiMessagesSendFileMessageConstMeta,
        argValues: [contactId, filePath, fileName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagesSendFileMessageConstMeta =>
      const TaskConstMeta(debugName: "send_file_message", argNames: ["contactId", "filePath", "fileName"]);

  @override
  Future<String> crateApiMessagesSendTextMessage({required String contactId, required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiMessagesSendTextMessageConstMeta,
        argValues: [contactId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagesSendTextMessageConstMeta =>
      const TaskConstMeta(debugName: "send_text_message", argNames: ["contactId", "content"]);

  @override
  String crateApiNetworkSetNetworkConfig({required int maxPeers, required int port}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(maxPeers, serializer);
          sse_encode_u_16(port, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkSetNetworkConfigConstMeta,
        argValues: [maxPeers, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSetNetworkConfigConstMeta =>
      const TaskConstMeta(debugName: "set_network_config", argNames: ["maxPeers", "port"]);

  @override
  String crateApiCoreShutdownCore() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiCoreShutdownCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreShutdownCoreConstMeta => const TaskConstMeta(debugName: "shutdown_core", argNames: []);

  @override
  String crateApiNetworkStartDiscovery() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkStartDiscoveryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStartDiscoveryConstMeta =>
      const TaskConstMeta(debugName: "start_discovery", argNames: []);

  @override
  Future<String> crateApiEventsStartEventListener() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiEventsStartEventListenerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventsStartEventListenerConstMeta =>
      const TaskConstMeta(debugName: "start_event_listener", argNames: []);

  @override
  Future<String> crateApiCoreStartServer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiCoreStartServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreStartServerConstMeta => const TaskConstMeta(debugName: "start_server", argNames: []);

  @override
  String crateApiNetworkStopDiscovery() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiNetworkStopDiscoveryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStopDiscoveryConstMeta =>
      const TaskConstMeta(debugName: "stop_discovery", argNames: []);

  @override
  Future<String> crateApiContactsUpdateContactTrustLevel({required String contactId, required TrustLevel trustLevel}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_trust_level(trustLevel, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiContactsUpdateContactTrustLevelConstMeta,
        argValues: [contactId, trustLevel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContactsUpdateContactTrustLevelConstMeta =>
      const TaskConstMeta(debugName: "update_contact_trust_level", argNames: ["contactId", "trustLevel"]);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppEvent dco_decode_app_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AppEvent_Network(dco_decode_box_autoadd_network_event(raw[1]));
      case 1:
        return AppEvent_Storage(dco_decode_box_autoadd_storage_event(raw[1]));
      case 2:
        return AppEvent_Crypto(dco_decode_box_autoadd_crypto_event(raw[1]));
      case 3:
        return AppEvent_Custom(
          eventType: dco_decode_String(raw[1]),
          data: dco_decode_String(raw[2]),
          timestamp: dco_decode_u_64(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Chrono_Utc(raw);
  }

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_message(raw);
  }

  @protected
  Contact dco_decode_box_autoadd_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_contact(raw);
  }

  @protected
  CryptoEvent dco_decode_box_autoadd_crypto_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_crypto_event(raw);
  }

  @protected
  NetworkEvent dco_decode_box_autoadd_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_network_event(raw);
  }

  @protected
  StorageEvent dco_decode_box_autoadd_storage_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_storage_event(raw);
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ChatMessage(
      id: dco_decode_String(arr[0]),
      from: dco_decode_String(arr[1]),
      to: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      msgType: dco_decode_chat_message_type(arr[4]),
      timestamp: dco_decode_u_64(arr[5]),
      deliveryStatus: dco_decode_delivery_status(arr[6]),
    );
  }

  @protected
  ChatMessageType dco_decode_chat_message_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatMessageType.values[raw as int];
  }

  @protected
  Contact dco_decode_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Contact(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      status: dco_decode_contact_status(arr[3]),
      trustLevel: dco_decode_trust_level(arr[4]),
      lastSeen: dco_decode_opt_box_autoadd_Chrono_Utc(arr[5]),
    );
  }

  @protected
  ContactStatus dco_decode_contact_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ContactStatus.values[raw as int];
  }

  @protected
  CryptoEvent dco_decode_crypto_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CryptoEvent_KeyPairGenerated();
      case 1:
        return CryptoEvent_Error(error: dco_decode_String(raw[1]), operation: dco_decode_String(raw[2]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DeliveryStatus dco_decode_delivery_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeliveryStatus.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<AppEvent> dco_decode_list_app_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_event).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  List<Contact> dco_decode_list_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_contact).toList();
  }

  @protected
  List<PeerData> dco_decode_list_peer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_data).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NetworkEvent_ServerStarted(port: dco_decode_u_16(raw[1]));
      case 1:
        return NetworkEvent_ServerStopped();
      case 2:
        return NetworkEvent_MessageReceived(message: dco_decode_box_autoadd_chat_message(raw[1]));
      case 3:
        return NetworkEvent_ContactAdded(contact: dco_decode_box_autoadd_contact(raw[1]));
      case 4:
        return NetworkEvent_Error(error: dco_decode_String(raw[1]), context: dco_decode_opt_String(raw[2]));
      case 5:
        return NetworkEvent_Debug(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NetworkStats dco_decode_network_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return NetworkStats(
      connectedPeers: dco_decode_u_32(arr[0]),
      totalMessagesSent: dco_decode_u_64(arr[1]),
      totalMessagesReceived: dco_decode_u_64(arr[2]),
      bytesSent: dco_decode_u_64(arr[3]),
      bytesReceived: dco_decode_u_64(arr[4]),
      uptimeSeconds: dco_decode_u_64(arr[5]),
      messagesSent: dco_decode_u_64(arr[6]),
      messagesReceived: dco_decode_u_64(arr[7]),
      totalConnections: dco_decode_u_32(arr[8]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  PeerData dco_decode_peer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8) throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PeerData(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[3]),
      connectedAt: dco_decode_Chrono_Utc(arr[4]),
      lastSeen: dco_decode_Chrono_Utc(arr[5]),
      bytesSent: dco_decode_u_64(arr[6]),
      bytesReceived: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  StorageEvent dco_decode_storage_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StorageEvent_ContactsSaved(count: dco_decode_usize(raw[1]));
      case 1:
        return StorageEvent_ContactsLoaded(count: dco_decode_usize(raw[1]));
      case 2:
        return StorageEvent_ChatHistorySaved(chatId: dco_decode_String(raw[1]), messageCount: dco_decode_usize(raw[2]));
      case 3:
        return StorageEvent_ChatHistoryLoaded(
          chatId: dco_decode_String(raw[1]),
          messageCount: dco_decode_usize(raw[2]),
        );
      case 4:
        return StorageEvent_CleanupCompleted(removedItems: dco_decode_usize(raw[1]));
      case 5:
        return StorageEvent_BackupCreated(filePath: dco_decode_String(raw[1]));
      case 6:
        return StorageEvent_Error(error: dco_decode_String(raw[1]), operation: dco_decode_String(raw[2]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TrustLevel dco_decode_trust_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrustLevel.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppEvent sse_decode_app_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_network_event(deserializer);
        return AppEvent_Network(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_storage_event(deserializer);
        return AppEvent_Storage(var_field0);
      case 2:
        var var_field0 = sse_decode_box_autoadd_crypto_event(deserializer);
        return AppEvent_Crypto(var_field0);
      case 3:
        var var_eventType = sse_decode_String(deserializer);
        var var_data = sse_decode_String(deserializer);
        var var_timestamp = sse_decode_u_64(deserializer);
        return AppEvent_Custom(eventType: var_eventType, data: var_data, timestamp: var_timestamp);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Chrono_Utc(deserializer));
  }

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_message(deserializer));
  }

  @protected
  Contact sse_decode_box_autoadd_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_contact(deserializer));
  }

  @protected
  CryptoEvent sse_decode_box_autoadd_crypto_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_crypto_event(deserializer));
  }

  @protected
  NetworkEvent sse_decode_box_autoadd_network_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_network_event(deserializer));
  }

  @protected
  StorageEvent sse_decode_box_autoadd_storage_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_storage_event(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_msgType = sse_decode_chat_message_type(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_deliveryStatus = sse_decode_delivery_status(deserializer);
    return ChatMessage(
      id: var_id,
      from: var_from,
      to: var_to,
      content: var_content,
      msgType: var_msgType,
      timestamp: var_timestamp,
      deliveryStatus: var_deliveryStatus,
    );
  }

  @protected
  ChatMessageType sse_decode_chat_message_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ChatMessageType.values[inner];
  }

  @protected
  Contact sse_decode_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_status = sse_decode_contact_status(deserializer);
    var var_trustLevel = sse_decode_trust_level(deserializer);
    var var_lastSeen = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    return Contact(
      id: var_id,
      name: var_name,
      address: var_address,
      status: var_status,
      trustLevel: var_trustLevel,
      lastSeen: var_lastSeen,
    );
  }

  @protected
  ContactStatus sse_decode_contact_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ContactStatus.values[inner];
  }

  @protected
  CryptoEvent sse_decode_crypto_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CryptoEvent_KeyPairGenerated();
      case 1:
        var var_error = sse_decode_String(deserializer);
        var var_operation = sse_decode_String(deserializer);
        return CryptoEvent_Error(error: var_error, operation: var_operation);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DeliveryStatus sse_decode_delivery_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DeliveryStatus.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<AppEvent> sse_decode_list_app_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<Contact> sse_decode_list_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Contact>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_contact(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerData> sse_decode_list_peer_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_data(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_port = sse_decode_u_16(deserializer);
        return NetworkEvent_ServerStarted(port: var_port);
      case 1:
        return NetworkEvent_ServerStopped();
      case 2:
        var var_message = sse_decode_box_autoadd_chat_message(deserializer);
        return NetworkEvent_MessageReceived(message: var_message);
      case 3:
        var var_contact = sse_decode_box_autoadd_contact(deserializer);
        return NetworkEvent_ContactAdded(contact: var_contact);
      case 4:
        var var_error = sse_decode_String(deserializer);
        var var_context = sse_decode_opt_String(deserializer);
        return NetworkEvent_Error(error: var_error, context: var_context);
      case 5:
        var var_message = sse_decode_String(deserializer);
        return NetworkEvent_Debug(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NetworkStats sse_decode_network_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connectedPeers = sse_decode_u_32(deserializer);
    var var_totalMessagesSent = sse_decode_u_64(deserializer);
    var var_totalMessagesReceived = sse_decode_u_64(deserializer);
    var var_bytesSent = sse_decode_u_64(deserializer);
    var var_bytesReceived = sse_decode_u_64(deserializer);
    var var_uptimeSeconds = sse_decode_u_64(deserializer);
    var var_messagesSent = sse_decode_u_64(deserializer);
    var var_messagesReceived = sse_decode_u_64(deserializer);
    var var_totalConnections = sse_decode_u_32(deserializer);
    return NetworkStats(
      connectedPeers: var_connectedPeers,
      totalMessagesSent: var_totalMessagesSent,
      totalMessagesReceived: var_totalMessagesReceived,
      bytesSent: var_bytesSent,
      bytesReceived: var_bytesReceived,
      uptimeSeconds: var_uptimeSeconds,
      messagesSent: var_messagesSent,
      messagesReceived: var_messagesReceived,
      totalConnections: var_totalConnections,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Chrono_Utc(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerData sse_decode_peer_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_connectedAt = sse_decode_Chrono_Utc(deserializer);
    var var_lastSeen = sse_decode_Chrono_Utc(deserializer);
    var var_bytesSent = sse_decode_u_64(deserializer);
    var var_bytesReceived = sse_decode_u_64(deserializer);
    return PeerData(
      id: var_id,
      name: var_name,
      address: var_address,
      publicKey: var_publicKey,
      connectedAt: var_connectedAt,
      lastSeen: var_lastSeen,
      bytesSent: var_bytesSent,
      bytesReceived: var_bytesReceived,
    );
  }

  @protected
  StorageEvent sse_decode_storage_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_count = sse_decode_usize(deserializer);
        return StorageEvent_ContactsSaved(count: var_count);
      case 1:
        var var_count = sse_decode_usize(deserializer);
        return StorageEvent_ContactsLoaded(count: var_count);
      case 2:
        var var_chatId = sse_decode_String(deserializer);
        var var_messageCount = sse_decode_usize(deserializer);
        return StorageEvent_ChatHistorySaved(chatId: var_chatId, messageCount: var_messageCount);
      case 3:
        var var_chatId = sse_decode_String(deserializer);
        var var_messageCount = sse_decode_usize(deserializer);
        return StorageEvent_ChatHistoryLoaded(chatId: var_chatId, messageCount: var_messageCount);
      case 4:
        var var_removedItems = sse_decode_usize(deserializer);
        return StorageEvent_CleanupCompleted(removedItems: var_removedItems);
      case 5:
        var var_filePath = sse_decode_String(deserializer);
        return StorageEvent_BackupCreated(filePath: var_filePath);
      case 6:
        var var_error = sse_decode_String(deserializer);
        var var_operation = sse_decode_String(deserializer);
        return StorageEvent_Error(error: var_error, operation: var_operation);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TrustLevel sse_decode_trust_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TrustLevel.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(PlatformInt64Util.from(self.microsecondsSinceEpoch), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_event(AppEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AppEvent_Network(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_network_event(field0, serializer);
      case AppEvent_Storage(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_storage_event(field0, serializer);
      case AppEvent_Crypto(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_crypto_event(field0, serializer);
      case AppEvent_Custom(eventType: final eventType, data: final data, timestamp: final timestamp):
        sse_encode_i_32(3, serializer);
        sse_encode_String(eventType, serializer);
        sse_encode_String(data, serializer);
        sse_encode_u_64(timestamp, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Chrono_Utc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_contact(Contact self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_contact(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_crypto_event(CryptoEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crypto_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_network_event(NetworkEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_network_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_storage_event(StorageEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_storage_event(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_chat_message_type(self.msgType, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_delivery_status(self.deliveryStatus, serializer);
  }

  @protected
  void sse_encode_chat_message_type(ChatMessageType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_contact(Contact self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_contact_status(self.status, serializer);
    sse_encode_trust_level(self.trustLevel, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.lastSeen, serializer);
  }

  @protected
  void sse_encode_contact_status(ContactStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_crypto_event(CryptoEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CryptoEvent_KeyPairGenerated():
        sse_encode_i_32(0, serializer);
      case CryptoEvent_Error(error: final error, operation: final operation):
        sse_encode_i_32(1, serializer);
        sse_encode_String(error, serializer);
        sse_encode_String(operation, serializer);
    }
  }

  @protected
  void sse_encode_delivery_status(DeliveryStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_app_event(List<AppEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(List<ChatMessage> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_contact(List<Contact> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_contact(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_data(List<PeerData> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NetworkEvent_ServerStarted(port: final port):
        sse_encode_i_32(0, serializer);
        sse_encode_u_16(port, serializer);
      case NetworkEvent_ServerStopped():
        sse_encode_i_32(1, serializer);
      case NetworkEvent_MessageReceived(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_chat_message(message, serializer);
      case NetworkEvent_ContactAdded(contact: final contact):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_contact(contact, serializer);
      case NetworkEvent_Error(error: final error, context: final context):
        sse_encode_i_32(4, serializer);
        sse_encode_String(error, serializer);
        sse_encode_opt_String(context, serializer);
      case NetworkEvent_Debug(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_network_stats(NetworkStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.connectedPeers, serializer);
    sse_encode_u_64(self.totalMessagesSent, serializer);
    sse_encode_u_64(self.totalMessagesReceived, serializer);
    sse_encode_u_64(self.bytesSent, serializer);
    sse_encode_u_64(self.bytesReceived, serializer);
    sse_encode_u_64(self.uptimeSeconds, serializer);
    sse_encode_u_64(self.messagesSent, serializer);
    sse_encode_u_64(self.messagesReceived, serializer);
    sse_encode_u_32(self.totalConnections, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(DateTime? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Chrono_Utc(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_data(PeerData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_Chrono_Utc(self.connectedAt, serializer);
    sse_encode_Chrono_Utc(self.lastSeen, serializer);
    sse_encode_u_64(self.bytesSent, serializer);
    sse_encode_u_64(self.bytesReceived, serializer);
  }

  @protected
  void sse_encode_storage_event(StorageEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StorageEvent_ContactsSaved(count: final count):
        sse_encode_i_32(0, serializer);
        sse_encode_usize(count, serializer);
      case StorageEvent_ContactsLoaded(count: final count):
        sse_encode_i_32(1, serializer);
        sse_encode_usize(count, serializer);
      case StorageEvent_ChatHistorySaved(chatId: final chatId, messageCount: final messageCount):
        sse_encode_i_32(2, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_usize(messageCount, serializer);
      case StorageEvent_ChatHistoryLoaded(chatId: final chatId, messageCount: final messageCount):
        sse_encode_i_32(3, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_usize(messageCount, serializer);
      case StorageEvent_CleanupCompleted(removedItems: final removedItems):
        sse_encode_i_32(4, serializer);
        sse_encode_usize(removedItems, serializer);
      case StorageEvent_BackupCreated(filePath: final filePath):
        sse_encode_i_32(5, serializer);
        sse_encode_String(filePath, serializer);
      case StorageEvent_Error(error: final error, operation: final operation):
        sse_encode_i_32(6, serializer);
        sse_encode_String(error, serializer);
        sse_encode_String(operation, serializer);
    }
  }

  @protected
  void sse_encode_trust_level(TrustLevel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
