// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class StorageStats {
  final BigInt totalContacts;
  final BigInt totalMessages;
  final BigInt storageSizeBytes;
  final DateTime? lastBackup;

  const StorageStats({
    required this.totalContacts,
    required this.totalMessages,
    required this.storageSizeBytes,
    this.lastBackup,
  });

  @override
  int get hashCode => totalContacts.hashCode ^ totalMessages.hashCode ^ storageSizeBytes.hashCode ^ lastBackup.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageStats &&
          runtimeType == other.runtimeType &&
          totalContacts == other.totalContacts &&
          totalMessages == other.totalMessages &&
          storageSizeBytes == other.storageSizeBytes &&
          lastBackup == other.lastBackup;
}
