// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Contact addContact({required String name, required String publicKey}) =>
    RustLib.instance.api.crateApiContactsAddContact(name: name, publicKey: publicKey);

String removeContact({required String contactId}) =>
    RustLib.instance.api.crateApiContactsRemoveContact(contactId: contactId);

List<Contact> getContacts() => RustLib.instance.api.crateApiContactsGetContacts();

Contact getContactById({required String contactId}) =>
    RustLib.instance.api.crateApiContactsGetContactById(contactId: contactId);

String updateContactName({required String contactId, required String newName}) =>
    RustLib.instance.api.crateApiContactsUpdateContactName(contactId: contactId, newName: newName);

String blockContact({required String contactId}) =>
    RustLib.instance.api.crateApiContactsBlockContact(contactId: contactId);

String unblockContact({required String contactId}) =>
    RustLib.instance.api.crateApiContactsUnblockContact(contactId: contactId);
