// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../storage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String initCore() => RustLib.instance.api.crateApiCoreInitCore();

String shutdownCore() => RustLib.instance.api.crateApiCoreShutdownCore();

bool isCoreInitialized() => RustLib.instance.api.crateApiCoreIsCoreInitialized();

String getMyPublicKey() => RustLib.instance.api.crateApiCoreGetMyPublicKey();

StorageStats getStorageStats() => RustLib.instance.api.crateApiCoreGetStorageStats();
