// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String sendTextMessage({required String contactId, required String content}) =>
    RustLib.instance.api.crateApiMessagesSendTextMessage(contactId: contactId, content: content);

List<ChatMessage> getMessages({required String contactId}) =>
    RustLib.instance.api.crateApiMessagesGetMessages(contactId: contactId);

List<ChatMessage> getRecentMessages({required String contactId, required int limit}) =>
    RustLib.instance.api.crateApiMessagesGetRecentMessages(contactId: contactId, limit: limit);

String markMessageAsRead({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesMarkMessageAsRead(messageId: messageId);

String deleteMessage({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesDeleteMessage(messageId: messageId);

int getUnreadMessageCount({required String contactId}) =>
    RustLib.instance.api.crateApiMessagesGetUnreadMessageCount(contactId: contactId);

List<ChatMessage> searchMessages({required String query, String? contactId}) =>
    RustLib.instance.api.crateApiMessagesSearchMessages(query: query, contactId: contactId);

ChatMessage getMessageById({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesGetMessageById(messageId: messageId);
